[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.2.0"
rayon = "1.10.0"
stb_image = "0.3.0"
spider_eye = { path = "../spider_eye" }
smol_str = "0.3.2"
fast-math = "0.1.1"

[profile.release-with-debug]
inherits = "release"
debug = true
